version: '3.9'

services:
  # --------------------------------------
  # Postgres
  # --------------------------------------
  pgsql:
    image: postgres:13.0-alpine
    container_name: pgsql
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - server_network
  # --------------------------------------
  # Application
  # --------------------------------------
  web:
    build: .
    container_name: web
    restart: always
    command: python manage.py runserver 0.0.0.0:8009 celery -A todo worker -l INFO
    volumes:
      - ./todo:/usr/src/app
    ports:
      - "8009:8009"
    env_file:
      - .env
    depends_on:
      - pgsql
      - rabbitmq
    networks:
      - server_network
  # --------------------------------------
  # Nginx
  # --------------------------------------
  nginx:
    build: ./docker/nginx/
    container_name: nginx
    restart: on-failure
    ports:
      - "81:81"
    depends_on:
      - web
    networks:
      - server_network
  # --------------------------------------
  # RabbitMQ
  # --------------------------------------
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - server_network

networks:
  server_network:
    driver: bridge