# Generated by Django 4.0.5 on 2022-06-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Task Title')),
                ('description', models.TextField(verbose_name='Task Description')),
                ('status', models.BooleanField(choices=[(True, 'Done'), (False, 'Undone')], default=False, verbose_name='Task Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Task Created')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['created_at'],
            },
        ),
    ]
